### ISSUE TITLE
AMD.Memory.Tweak.XL

### ISSUE THREAD

**Issue by gennadiv** [Eliovp/AMDMemoryTweakXL#1]
does not work with Adrenalin 2019 Edition 19.7.3 Optional drivers

**Comment by Eliovp** [comment]
I will do some more tests in the upcoming week to get most bugs out

**Comment by gennadiv** [comment]
> Я сделаю еще несколько тестов на следующей неделе, чтобы получить большинство ошибок

**Comment by gennadiv** [comment]
https://pastenow.ru/687WT

**Comment by gennadiv** [comment]
> Я сделаю еще несколько тестов на следующей неделе, чтобы получить большинство ошибок

https://pastenow.ru/687WT

**Comment by Eliovp** [comment]
Try latest release

[Here](https://github.com/Eliovp/AMDMemoryTweakXL/releases/tag/1.0.0.1)

**Comment by gennadiv** [comment]
> Попробуйте последнюю версию
> 
> [Здесь](https://github.com/Eliovp/AMDMemoryTweakXL/releases/tag/1.0.0.1)

this version works.thank you,I'm very impressed

**Comment by Eliovp** [comment]
👍  Have fun!
